# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Production frontend app service

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'doc/**'
      - '.github/agents/**'
      - '*.md'
      - 'CONTRIBUTING.md'
      - 'README.md'
      - 'GLOSSARY.md'
      - 'AGENTS.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'slot2'
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v6

      - name: Set up Node.js version
        uses: actions/setup-node@v6
        with:
          node-version: '20.x'

      - name: Cache node modules
        uses: actions/cache@v5
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: yarn install, pull webflow files and build
        run: |
          cd frontend
          yarn --production
          npx webflow devlink sync --no-input
          yarn build
        env:
          API_HOST: ${{ secrets.API_HOST }}
          CUSTOM_HUB_URLS: ${{ secrets.CUSTOM_HUB_URLS }}
          API_URL: ${{ secrets.API_URL }}
          BASE_URL_HOST: ${{ secrets.BASE_URL_HOST }}
          BASE_URL: ${{ secrets.BASE_URL }}
          DONATION_CAMPAIGN_RUNNING: ${{ secrets.DONATION_CAMPAIGN_RUNNING }}
          ENVIRONMENT: 'production'
          GOOGLE_ANALYTICS_CODE: ${{ secrets.GOOGLE_ANALYTICS_CODE }}
          LATEST_NEWSLETTER_LINK: ${{ secrets.LATEST_NEWSLETTER_LINK }}
          LETS_ENCRYPT_FILE_CONTENT: ${{ secrets.LETS_ENCRYPT_FILE_CONTENT }}
          LOCATION_HUBS: ${{ secrets.LOCATION_HUBS }}
          SOCKET_URL: ${{ secrets.SOCKET_URL }}
          WEBFLOW_API_TOKEN: ${{ secrets.WEBFLOW_API_TOKEN }}
          WEBFLOW_SITE_ID: ${{ secrets.WEBFLOW_SITE_ID}}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v6
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'slot2'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v7
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4872F38E7EC34E84A6DC4282AD368DAE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_03DE6874FBFC4E709867040CB9136FD8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_127807AFF9E54FB49F85724A33EB8088 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'climateconnect-frontend-appservice'
          slot-name: 'slot2'
          package: .
